ldap:
  server: dc01.ciscocollab.ninja
  port: 636
  ssl: True
  username: svc-ldap@ciscocollab.ninja
  password: Ciscocollab41!
  searchbase: DC=ciscocollab,DC=ninja
  querygroup: (&(memberof=CN=Compliance Users,CN=Users,DC=ciscocollab,DC=ninja))
  attribute: sAMAccountName
mail:
  server: smtp.office365.com
  port: 587
  auth: cclouse@ciscocollab.ninja
  password:
  sender: cclouse@ciscocollab.ninja
  recipient: cclouse@ciscocollab.ninja
uds:
  server: cucm2.ciscocollab.ninja
axl1:
  username: axl-cer
  password: ccievoice
  server_ip: 192.168.10.200
axl2:
  username: axlapi
  password: ccievoice
  server_ip: 192.168.10.220
axl3:
  username: axlapi
  password: ccievoice
  server_ip:
axl4:
  username: axlapi
  password: ccievoice
  server_ip:
