ldap:
  server: dc01.ciscocollab.ninja
  port: 636
  ssl: True
  username: svc-ldap@ciscocollab.ninja
  password: Ciscocollab41!
  searchbase: DC=ciscocollab,DC=ninja
  querygroup: (&(memberof=CN=Compliance Users,CN=Users,DC=ciscocollab,DC=ninja))
  attribute: sAMAccountName
mail:
  server: smtp.office365.com
  port: 587
  auth_required: False
  auth_username: cclouse@ciscocollab.ninja
  auth_password:
  sender: cclouse@ciscocollab.ninja
  recipient: cclouse@ciscocollab.ninja
uds:
  server:
cucm:
  primary_uds_server: cucm2.ciscocollab.ninja
  cluster1:
    username: axl-cer
    password: ccievoice
    server_ip: 192.168.10.200
  cluster2:
    username: axlapi
    password: ccievoice
    server_ip: 192.168.10.220
  cluster3:
    username:
    password:
    server_ip:
  cluster4:
    username:
    password:
    server_ip: